CREATE DATABASE IF NOT EXISTS friend_portfolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE friend_portfolio;


CREATE TABLE IF NOT EXISTS contacts (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
email VARCHAR(200) NOT NULL,
message TEXT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;